
/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include "ETH2.h"
#include <g3log/g3log.hpp>
#include "ModelCore/Common/Async/WaitHandle.h"
#include "ModelCore/ExecutionEngine/Task.h"
#include "ModelCore/ExecutionEngine/Priority.h"
#include "ModelCore/ExecutionEngine/PriorityQuery.h"
#include "ModelCore/ExecutionEngine/Services/SchedulerService.h"

EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2::ETH2(const ::std::vector<::std::string> labels) :
		::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core(labels)
{
}

EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2::~ETH2()
{
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2::register_processes()
{
	const auto scheduler_service = ::model_core::common::service::find_service<::model_core::execution_engine::services::SchedulerService>();

	// Register: P195 with priority 'init_P195' at task 'Init'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Init", "init_P195");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2),"
			<< " Task: 'Init',"
			<< " Priority: 'init_P195',"
			<< " Process: 'P195'";
		priority->create_action(
			this->get_module_path() +  "->P195", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P195(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P195" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P360 with priority 'send_P360' at task 'SendFR'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("SendFR", "send_P360");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2),"
			<< " Task: 'SendFR',"
			<< " Priority: 'send_P360',"
			<< " Process: 'P360'";
		priority->create_action(
			this->get_module_path() +  "->P360", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P360(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P360" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P380 with priority 'send_P380' at task 'SendFR'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("SendFR", "send_P380");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2),"
			<< " Task: 'SendFR',"
			<< " Priority: 'send_P380',"
			<< " Process: 'P380'";
		priority->create_action(
			this->get_module_path() +  "->P380", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P380(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P380" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P380_1 with priority 'send_P380' at task 'Send'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Send", "send_P380");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2),"
			<< " Task: 'Send',"
			<< " Priority: 'send_P380',"
			<< " Process: 'P380_1'";
		priority->create_action(
			this->get_module_path() +  "->P380_1", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P380_1(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P380_1" << ": " << e.what();
					throw e;
				}
			});
	}
}
void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2::register_signal_connections()
{
#ifndef IGNORE_DEFAULT_SIGNAL_SYNC
#else
	::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::register_signal_connections();
#endif
}
