
/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#pragma once

#include "ETH2Core.h"
#include "ModelCore/Common/Time/SimulationTime.h"

namespace EID
{
    namespace Net
    {
        namespace ETH
        {
            namespace GM_BEV3_205_9p9_V01_M
            {
                class DLL_EXPORT_COMPONENT ETH2 : public ::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core
                {
                public:	// Local processes
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P195
                	/// Task:			Init
                	///	Priority:		init_P195
                	/// </summary>
                	void P195(::model_core::common::time::SimulationTime* time_info);
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P360
                	/// Task:			SendFR
                	///	Priority:		send_P360
                	/// </summary>
                	void P360(::model_core::common::time::SimulationTime* time_info);
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P380
                	/// Task:			SendFR
                	///	Priority:		send_P380
                	/// </summary>
                	void P380(::model_core::common::time::SimulationTime* time_info);
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P380_1
                	/// Task:			Send
                	///	Priority:		send_P380
                	/// </summary>
                	void P380_1(::model_core::common::time::SimulationTime* time_info);
                
                public: // Common methods
                
                	/*! \copydoc */
                	void register_processes() override;
                	
                
                	/*! \copydoc */
                	void register_signal_connections() override;
                
                
                public:	// Constructors
                
                	/*! \brief Constructor. 
                	 *
                	 *  The component can be used as:
                	 *    - EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2
                	*/
                	explicit ETH2(const ::std::vector<::std::string> labels);
                			   	
                	/*! \brief Destructor. */
                	virtual ~ETH2();
                }; // END OF CLASS: ETH2
            } // END OF NAMESPACE: GM_BEV3_205_9p9_V01_M
        } // END OF NAMESPACE: ETH
    } // END OF NAMESPACE: Net
} // END OF NAMESPACE: EID
