/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#pragma once

#include "Base/ETH2Base.h"
#include "Global/Global.h"

#include "XmlSignalReader/XmlSignalReader.h"
#include "Defs/ModelData.h"
#include "Defs/ManipHelperClass.h"
#include "Global/macros.h"

using namespace model_core::model_access;
namespace HwLight = Plugins::FlexCard3::PC_HW_Interface::Light;
namespace HwSerializer = Plugins::FlexCard3::PC_HW_Interface::Light::HwSerializer;

namespace EID
{
	namespace Net
	{
		namespace ETH
		{
			namespace GM_BEV3_205_9p9_V01_M
			{
				class DLL_EXPORT_COMPONENT ETH2Core : public ::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Base
				{
				public:
					std::string nodeName = "";  // NOLINT(readability-redundant-string-init)
					const std::string STAR_PREFIX{ "FC3: " };
					uint32_t cardNumber = 1;
					u08 wait = 0;
					bool success;
					bool WuP_Cyclic_Control = false;
					bool Init = false;

					HwLight::HwComDataObject<void, 0> read_Index{ 0 };
					uint16_t readSlot_Index = 0;

					// ETH2 Frames HwComDataObjects (address set from XML)
					HwLight::HwComDataObject<void, 0> ETH2_Frame_WuP{ 0 };				//0xFD
					HwLight::HwComDataObject<void, 0> ETH2_Frame_Heartbeat{ 0 };		//0xFE
					HwLight::HwComDataObject<void, 0> ETH2_Frame_Info{ 0 };				//0xFF

					// ETH2 PDUs HwComDataObjects (address set from XML)
					HwLight::HwComDataObject<void, 36> ETH2_PDU_WuP{ 0 };				//0xFD
					HwLight::HwComDataObject<void, 18> ETH2_PDU_Heartbeat{ 0 };			//0xFE
					HwLight::HwComDataObject<void, 28> ETH2_PDU_Info{ 0 };				//0xFF

					// ETH2 Custom Timings for PDUs HwComDataObjects (address set from XML)
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> ETH2_Custom_Timing_WuP{ 0 };				//0xFD
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> ETH2_Custom_Timing_Heartbeat{ 0 };			//0xFE
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> ETH2_Custom_Timing_Info{ 0 };				//0xFF

					// Global Variable HwComDataObjects (address set from XML)
					HwLight::HwComDataObject<uint8_t, 1> gVarAlternativeTiming{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarAlternativeTimingEth1{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarAlternativeTimingEth2{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarFcCounterValueSetAll{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarIgnitionState{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarSaveFreshnessAll{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarService3163Rcvd{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarService3164Rcvd{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarSetFreshnessAll{ 0 };
					HwLight::HwComDataObject<uint8_t, 1> gVarSetWuP{ 0 };

					//ETH2 Signals HwComDataObjects (address set from XML)
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstActrModeRfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_b_eBstPwrMgmtReqS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_v_eBstWhlSpdRrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_p_eBstBrkTgtRrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_p_eBstBrkTgtRfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstWhlSpdRrInvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_v_eBstWhlSpdLrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstVeh_AxInvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstRmtPrgActvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstActrModeLfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_v_eBstWhlSpdRfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_a_eBstVehAyS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_Pct_eBstAccelEffPosS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_M_eBstTotAxlTrqActS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstWhlSpdRfInvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstActrModeLrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstFuncTstAllwdS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_e_eBstBrkSysPwrModeS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_p_eBstBrkTgtLfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstBrkCmdTypeLrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_p_eBstBrkTgtLrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstOAT_InvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstActrModeRrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_e_eBstEPB_CmdS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_T_eBstOAT_CorrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_I_eBstPwrMgmtGenLimS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstWhlSpdLfInvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_F_eBstEPB_StateCmdRtS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstBrkCmdTypeLfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_l_eBstVehOdoBCM_S_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_F_eBstEPB_StateCmdLtS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_v_eBstWhlSpdLfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstWhlSpdLrInvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_I_eBstPwrMgmtSinkLimS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_a_eBstVeh_AxS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstBrkCmdTypeRrS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_phi_eBstStrWhlAngS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstTransSIP_S_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstHydFuncStCmdS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstBrkCmdTypeRfS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstWrmUpCyclCmptS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_e_eBstTransLvrPstnS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstRnCrnkActBkupS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_e_eBstPriPwrModeS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_e_eBstBkupPwrModeS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_PropSysActvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_y_eBstVehRegionCodeS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_v_eBstVehicleS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstRnCrnkActPriS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_V_eBstRplnshVolTrgtS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2SSMR_0C5A8001_0D8B8001_QoS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_p_eBstBkPrsTgtBaseS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2YeBACR_e_eBstBrkOprtnRqstS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2NeBACR_t_eBstPropSysInactvS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2NeBACR_b_eBstBrkFdSt2DiagS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_b_eBstEPB_HpoAvailS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2NeBACR_b_eBstBrkFdSt1DiagS_Signal{ 0 };
					HwLight::HwComDataObject<double, 8> eth2VeBACR_e_eBstRplnshTriggerS_Signal{ 0 };

					// Generic processing helpers
					std::unordered_map<std::string, std::reference_wrapper<decltype(eth2YeBACR_e_eBstActrModeRfS_Signal)>> eth2HwSignalMap;
					std::unordered_map<std::string, double> eth2OldPhysValueMap;

					//Standard Interface
					std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_Base::PC_HW_Int_Base> pc_hw_int = nullptr;
					std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_V100::PC_HW_Int_V100> pc_hw_interface = nullptr;
					//Light Interface
					std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::Light::PC_HW_Int_Light::PC_HW_Int_Light> pc_hw_interface_light = nullptr;

					Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation* helper = Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation::getInstance();

					t_hw_com_light_value WakeUpValues2Set[2] = {};
					t_hw_com_light_value HeartBeatValues2Set[2] = {};
					t_hw_com_light_value InfoValues2Set[2] = {};
					HW_COM_LIGHT_PHYS_DATA AltTimingSetValue[2] = {};

					/////////////////////////////////////////PDUs/////////////////////////////////////////
					//VLAN 111
					const std::string HeartBeat_VLAN_111_PDU = "PDU_SYS_PMMulticastRxPwrMgrMulti_Heartbeat";
					const std::string WakeUp_VLAN_111_PDU = "PDU_SYS_PMMulticastRxPwrMgrMulti_Wakeup";

					//VLAN 23
					const std::string Info_PDU = "PDU_SYS_SMUnicastRxMechatronicsT1S_Eth2_Info";

					/////////////////////////////////////////Frames/////////////////////////////////////////
					//VLAN 111
					const std::string WakeUp_VLAN_111_Frame_Tx = "PDU_SYS_PMMulticastRxPwrMgrMulti_Wakeup";
					const std::string HeartBeat_VLAN_111_Frame_Tx = "SPDU_SYS_PMMulticastRxPwrMgrMulti_Heartbeat";

					//VLAN 23
					const std::string Info_Frame_Tx = "SPDU_SYS_SMUnicastRxMechatronicsT1S_Eth2_Info";

					void SignalListData();
					void PDUListData();
					void FRAMEListData();
					void GlobalVars_list();

				protected:
					Plugins::Global::Global globalPlugin;
					double cycleTimer;
					double cycleTimeWuPTickCount;
					double cycleTimeWuPInitTickCount;
					double cycleTimeHBTickCount;
					double cycleTimeInfoTickCount;
					double cycleTimeSomeIPTickCount;
					bool Info_activation = false;

					std::map<std::string, model_core::model::Signal*> moduloSignalList;
					std::vector<std::unique_ptr<Defs::ManipulationSignalHelperfloat>> FloatSigManipulationHelperList;

					//Frame list
					std::map<std::string, unsigned int> FrameManipList;
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> FrameList;
					std::map<std::string, SignalDataProcessing::Frame> sendFrameList;

					//PDU list
					std::map<std::string, unsigned int> PDUManipList;
					std::map<std::string, unsigned int> PDULengthList;
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> PDUSetList;
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> PDUGetList;
					std::map<std::string, SignalDataProcessing::PDU> sendPDUList;
					std::map<std::string, SignalDataProcessing::PDU> receivePDUList;

					//Signals Raw list
					std::map<std::string, unsigned int> signalGetRawList;
					std::map<std::string, unsigned int> signalLenRawList;
					std::map<std::string, unsigned int> signalSetRawList;

					//Signals phys list
					std::map<std::string, unsigned int> signalGetphysList;
					std::map<std::string, unsigned int> signalLenphysList;
					std::map<std::string, unsigned int> signalSetphysList;

					std::map<std::string, unsigned int> gVarLengthList;
					std::map<std::string, unsigned int> gVarSetList;
					std::map<std::string, unsigned int> gVarGetList;

					std::map<std::string, SignalDataProcessing::Signal> sendSignalsList_Raw;
					std::map<std::string, SignalDataProcessing::Signal> sendSignalsList_Phys;

					std::map<std::string, std::shared_ptr<IdValuePair<double>>> signalList_float_Phys;
					std::map<std::string, std::shared_ptr<IdValuePair<bool>>> signalList_bool_Phys;
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> signalList_float_Raw;
					std::map<std::string, std::shared_ptr<IdValuePair<bool>>> signalList_bool_Raw;
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> gVarList_Phys;

					std::vector<uint8_t> setRawPduWakeUpBuffer_V23 = {
						0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x00,
						0x0A, 0x17, 0x01, 0x81, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00
					};

					std::vector<uint8_t> setRawPduHBBuffer_V23 = {
						0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x00,
						0x0A, 0x17, 0x01, 0x81, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00
					};

					std::vector<uint8_t> setRawPduInfoBuffer_V23 = {
						0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x00,
						0x0A, 0x17, 0x01, 0x81, 0x0A, 0x17, 0x06, 0x21,
						0x00, 0x00, 0x06, 0x0C, 0x5B, 0x00, 0x01, 0x00,
						0x01, 0x01, 0x00, 0x00
					};

					void InitializeAllLists();
				private:
					void initialize();
					void uninitialize();

					DEFINE_COMPONENT_CORE_IMPLEMENTATION(ETH2)

				}; // END OF CLASS: ETH2
			} // END OF NAMESPACE: GM_BEV3_205_9p9_V01_M
		} // END OF NAMESPACE: ETH
	} // END OF NAMESPACE: Net
} // END OF NAMESPACE: EID