/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.ETH2
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#include "ETH2Core.h"
#include "Defs/ModelData.h"

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::ETH2Core::initialize()
{
	//read Node name
	const std::string moduleName = this->get_component_description().get_module_name();
	const auto found = moduleName.find_last_of('.'); //was "." (Linux?)
	nodeName = moduleName.substr(found + 1);

	moduloSignalList.clear();
	for (::model_core::model::Signal* moduloSignal : this->get_signals())
	{
		moduloSignalList.insert(std::make_pair(moduloSignal->get_name(), moduloSignal));
	}
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::ETH2Core::uninitialize()
{
	FloatSigManipulationHelperList.clear();
	eth2OldPhysValueMap.clear();
	eth2HwSignalMap.clear();
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::ETH2Core::InitializeAllLists()
{
	pc_hw_int = PC_HW_Int_Client->getPcHwIntLibVersion();
	pc_hw_interface_light = PC_HW_Int_Lt_Client->getPcHwIntLightVersion();

	SignalListData();
	PDUListData();
	FRAMEListData();
	GlobalVars_list();
	FloatSigManipulationHelperList.clear();
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::ETH2Core::SignalListData()
{
	auto signals_xml = helper->Get_readxml()->GetSetSignalList(nodeName.c_str());

	std::unordered_map<std::string, std::reference_wrapper<decltype(eth2VeBACR_b_eBstTransSIP_S_Signal)>> m
	{
		{"YeBACR_e_eBstActrModeRfS",      eth2YeBACR_e_eBstActrModeRfS_Signal},
		{"YeBACR_b_eBstPwrMgmtReqS",      eth2YeBACR_b_eBstPwrMgmtReqS_Signal},
		{"VeBACR_v_eBstWhlSpdRrS",        eth2VeBACR_v_eBstWhlSpdRrS_Signal},
		{"YeBACR_p_eBstBrkTgtRrS",        eth2YeBACR_p_eBstBrkTgtRrS_Signal},
		{"YeBACR_p_eBstBrkTgtRfS",        eth2YeBACR_p_eBstBrkTgtRfS_Signal},
		{"VeBACR_b_eBstWhlSpdRrInvS",     eth2VeBACR_b_eBstWhlSpdRrInvS_Signal},
		{"VeBACR_v_eBstWhlSpdLrS",        eth2VeBACR_v_eBstWhlSpdLrS_Signal},
		{"VeBACR_b_eBstVeh_AxInvS",       eth2VeBACR_b_eBstVeh_AxInvS_Signal},
		{"VeBACR_b_eBstRmtPrgActvS",      eth2VeBACR_b_eBstRmtPrgActvS_Signal},
		{"YeBACR_e_eBstActrModeLfS",      eth2YeBACR_e_eBstActrModeLfS_Signal},
		{"VeBACR_v_eBstWhlSpdRfS",        eth2VeBACR_v_eBstWhlSpdRfS_Signal},
		{"VeBACR_a_eBstVehAyS",           eth2VeBACR_a_eBstVehAyS_Signal},
		{"VeBACR_Pct_eBstAccelEffPosS",   eth2VeBACR_Pct_eBstAccelEffPosS_Signal},
		{"YeBACR_M_eBstTotAxlTrqActS",    eth2YeBACR_M_eBstTotAxlTrqActS_Signal},
		{"VeBACR_b_eBstWhlSpdRfInvS",     eth2VeBACR_b_eBstWhlSpdRfInvS_Signal},
		{"YeBACR_e_eBstActrModeLrS",      eth2YeBACR_e_eBstActrModeLrS_Signal},
		{"VeBACR_b_eBstFuncTstAllwdS",    eth2VeBACR_b_eBstFuncTstAllwdS_Signal},
		{"VeBACR_e_eBstBrkSysPwrModeS",   eth2VeBACR_e_eBstBrkSysPwrModeS_Signal},
		{"YeBACR_p_eBstBrkTgtLfS",        eth2YeBACR_p_eBstBrkTgtLfS_Signal},
		{"YeBACR_e_eBstBrkCmdTypeLrS",    eth2YeBACR_e_eBstBrkCmdTypeLrS_Signal},
		{"YeBACR_p_eBstBrkTgtLrS",        eth2YeBACR_p_eBstBrkTgtLrS_Signal},
		{"VeBACR_b_eBstOAT_InvS",         eth2VeBACR_b_eBstOAT_InvS_Signal},
		{"YeBACR_e_eBstActrModeRrS",      eth2YeBACR_e_eBstActrModeRrS_Signal},
		{"VeBACR_e_eBstEPB_CmdS",         eth2VeBACR_e_eBstEPB_CmdS_Signal},
		{"VeBACR_T_eBstOAT_CorrS",        eth2VeBACR_T_eBstOAT_CorrS_Signal},
		{"YeBACR_I_eBstPwrMgmtGenLimS",   eth2YeBACR_I_eBstPwrMgmtGenLimS_Signal},
		{"VeBACR_b_eBstWhlSpdLfInvS",     eth2VeBACR_b_eBstWhlSpdLfInvS_Signal},
		{"VeBACR_F_eBstEPB_StateCmdRtS",  eth2VeBACR_F_eBstEPB_StateCmdRtS_Signal},
		{"YeBACR_e_eBstBrkCmdTypeLfS",    eth2YeBACR_e_eBstBrkCmdTypeLfS_Signal},
		{"VeBACR_l_eBstVehOdoBCM_S",      eth2VeBACR_l_eBstVehOdoBCM_S_Signal},
		{"VeBACR_F_eBstEPB_StateCmdLtS",  eth2VeBACR_F_eBstEPB_StateCmdLtS_Signal},
		{"VeBACR_v_eBstWhlSpdLfS",        eth2VeBACR_v_eBstWhlSpdLfS_Signal},
		{"VeBACR_b_eBstWhlSpdLrInvS",     eth2VeBACR_b_eBstWhlSpdLrInvS_Signal},
		{"YeBACR_I_eBstPwrMgmtSinkLimS",  eth2YeBACR_I_eBstPwrMgmtSinkLimS_Signal},
		{"YeBACR_a_eBstVeh_AxS",          eth2YeBACR_a_eBstVeh_AxS_Signal},
		{"YeBACR_e_eBstBrkCmdTypeRrS",    eth2YeBACR_e_eBstBrkCmdTypeRrS_Signal},
		{"VeBACR_phi_eBstStrWhlAngS",     eth2VeBACR_phi_eBstStrWhlAngS_Signal},
		{"VeBACR_b_eBstTransSIP_S",       eth2VeBACR_b_eBstTransSIP_S_Signal},
		{"YeBACR_e_eBstHydFuncStCmdS",    eth2YeBACR_e_eBstHydFuncStCmdS_Signal},
		{"YeBACR_e_eBstBrkCmdTypeRfS",    eth2YeBACR_e_eBstBrkCmdTypeRfS_Signal},
		{"VeBACR_b_eBstWrmUpCyclCmptS",   eth2VeBACR_b_eBstWrmUpCyclCmptS_Signal},
		{"VeBACR_e_eBstTransLvrPstnS",    eth2VeBACR_e_eBstTransLvrPstnS_Signal},
		{"VeBACR_b_eBstRnCrnkActBkupS",   eth2VeBACR_b_eBstRnCrnkActBkupS_Signal},
		{"VeBACR_e_eBstPriPwrModeS",      eth2VeBACR_e_eBstPriPwrModeS_Signal},
		{"VeBACR_e_eBstBkupPwrModeS",     eth2VeBACR_e_eBstBkupPwrModeS_Signal},
		{"VeBACR_b_PropSysActvS",         eth2VeBACR_b_PropSysActvS_Signal},
		{"VeBACR_y_eBstVehRegionCodeS",   eth2VeBACR_y_eBstVehRegionCodeS_Signal},
		{"VeBACR_v_eBstVehicleS",         eth2VeBACR_v_eBstVehicleS_Signal},
		{"VeBACR_b_eBstRnCrnkActPriS",    eth2VeBACR_b_eBstRnCrnkActPriS_Signal},
		{"VeBACR_V_eBstRplnshVolTrgtS",   eth2VeBACR_V_eBstRplnshVolTrgtS_Signal},
		{"SSMR_0C5A8001_0D8B8001_QoS",    eth2SSMR_0C5A8001_0D8B8001_QoS_Signal},
		{"VeBACR_p_eBstBkPrsTgtBaseS",    eth2VeBACR_p_eBstBkPrsTgtBaseS_Signal},
		{"YeBACR_e_eBstBrkOprtnRqstS",    eth2YeBACR_e_eBstBrkOprtnRqstS_Signal},
		{"NeBACR_t_eBstPropSysInactvS",   eth2NeBACR_t_eBstPropSysInactvS_Signal},
		{"NeBACR_b_eBstBrkFdSt2DiagS",    eth2NeBACR_b_eBstBrkFdSt2DiagS_Signal},
		{"VeBACR_b_eBstEPB_HpoAvailS",    eth2VeBACR_b_eBstEPB_HpoAvailS_Signal},
		{"NeBACR_b_eBstBrkFdSt1DiagS",    eth2NeBACR_b_eBstBrkFdSt1DiagS_Signal},
		{"VeBACR_e_eBstRplnshTriggerS",   eth2VeBACR_e_eBstRplnshTriggerS_Signal},
	};

	signalSetphysList.clear();
	signalLenphysList.clear();
	signalList_float_Phys.clear();
	sendSignalsList_Phys.clear();
	eth2HwSignalMap.clear();
	eth2OldPhysValueMap.clear();


	for (const auto& sig : signals_xml)
	{
		signalSetphysList.emplace(sig.label, sig.set_phys);
		signalLenphysList.emplace(sig.label, sig.length_phys);

		auto physIdVal = std::make_shared<IdValuePair<double>>();
		std::string physCpName = sig.label + "__Sig";
		physIdVal->Id = sig.set_phys;
		physIdVal->Name = sig.label;
		physIdVal->Length = sig.length_phys;
		physIdVal->OldValue = sig.defValPhys > 0;
		signalList_float_Phys.emplace(physCpName, physIdVal);
		sendSignalsList_Phys.emplace(physCpName, sig);
		if (auto it = m.find(sig.label); it != m.end())
		{
			it->second.get().setAddress(sig.set_phys);
			eth2HwSignalMap.emplace(physCpName, it->second);
		}
		else
		{
			LOG(WARNING) << "SignalListData: no HwComDataObject found for XML label=" << sig.label;
		}
	}

	LOG(INFO) << "SignalListData: eth2HwSignalMap size=" << eth2HwSignalMap.size();
	LOG(INFO) << "SignalListData: signalList_float_Phys size=" << signalList_float_Phys.size();
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::FRAMEListData()
{
	auto frames_xml = helper->Get_readxml()->GetSetFrameList(nodeName.c_str());

	FrameManipList.clear();
	FrameList.clear();
	sendFrameList.clear();

	for (const auto& sig : frames_xml)
	{
		FrameManipList.emplace(sig.label, sig.setTx);

		auto idval = std::make_shared<IdValuePair<double>>();
		std::string cpName = sig.label + "__Frame";
		idval->Id = sig.setTx;
		idval->Name = sig.label;
		idval->Length = sig.Setlength;
		FrameList.emplace(cpName, idval);
		sendFrameList.emplace(cpName, sig);

		if (sig.label == WakeUp_VLAN_111_Frame_Tx)
		{
			ETH2_Frame_WuP.setAddress(sig.setTx);
			CommonVars->CCU_ETH2_WuP_Frm_Set_Address->quantity = none_t(ETH2_Frame_WuP.getAddress());
		}
		else if (sig.label == HeartBeat_VLAN_111_Frame_Tx)
		{
			ETH2_Frame_Heartbeat.setAddress(sig.setTx);
			CommonVars->CCU_ETH2_HB_Frm_Set_Address->quantity = none_t(ETH2_Frame_Heartbeat.getAddress());
		}
		else if (sig.label == Info_Frame_Tx)
		{
			ETH2_Frame_Info.setAddress(sig.setTx);
			CommonVars->CCU_ETH2_Info_Frm_Set_Address->quantity = none_t(ETH2_Frame_Info.getAddress());
		}
	}

	if (FrameList.empty())
	{
		LOG(INFO) << "ETH2 FrameList is empty.";
		return;
	}
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::PDUListData()
{
	auto pdus_xml = helper->Get_readxml()->GetSetPDUList(nodeName.c_str());

	PDUManipList.clear();
	PDULengthList.clear();
	PDUSetList.clear();
	PDUGetList.clear();
	sendPDUList.clear();
	receivePDUList.clear();

	for (const auto& sig : pdus_xml)
	{
		const unsigned int pduLengthBytes = sig.length / 8;

		PDUManipList.emplace(sig.label, sig.set);
		PDULengthList.emplace(sig.label, pduLengthBytes);

		auto setIdVal = std::make_shared<IdValuePair<double>>();
		std::string cpName = sig.label + "__PDU";
		setIdVal->Id = sig.set;
		setIdVal->Name = sig.label;
		setIdVal->Length = pduLengthBytes;
		PDUSetList.emplace(cpName, setIdVal);
		sendPDUList.emplace(cpName, sig);

		auto getIdVal = std::make_shared<IdValuePair<double>>();
		getIdVal->Id = sig.get;
		getIdVal->Name = sig.label;
		getIdVal->Length = pduLengthBytes;
		PDUGetList.emplace(cpName, getIdVal);
		receivePDUList.emplace(cpName, sig);

		if (sig.label == WakeUp_VLAN_111_PDU)
		{
			ETH2_PDU_WuP.setAddress(sig.set);
			ETH2_Custom_Timing_WuP.setAddress(sig.CustomTiming);

			CommonVars->CCU_ETH2_WuP_PDU_Set_Address->quantity = none_t(ETH2_PDU_WuP.getAddress());
			CommonVars->CCU_ETH2_WuP_PDU_Length->quantity = none_t(ETH2_PDU_WuP.getLength());
			CommonVars->CCU_ETH2_WuP_PDU_Custom_Timing->quantity = none_t(ETH2_Custom_Timing_WuP.getAddress());
		}
		else if (sig.label == HeartBeat_VLAN_111_PDU)
		{
			ETH2_PDU_Heartbeat.setAddress(sig.set);
			CommonVars->CCU_ETH2_HB_PDU_Set_Address->quantity = none_t(ETH2_PDU_Heartbeat.getAddress());
			CommonVars->CCU_ETH2_HB_PDU_Length->quantity = none_t(ETH2_PDU_Heartbeat.getLength());
		}
		else if (sig.label == Info_PDU)
		{
			ETH2_PDU_Info.setAddress(sig.set);
			CommonVars->CCU_ETH2_Info_PDU_Set_Address->quantity = none_t(ETH2_PDU_Info.getAddress());
			CommonVars->CCU_ETH2_Info_PDU_Length->quantity = none_t(ETH2_PDU_Info.getLength());
		}
	}

	if (PDUSetList.empty())
	{
		LOG(INFO) << "ETH2 PDUSetList is empty.";
		return;
	}
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ETH2Core::GlobalVars_list()
{
	gVarLengthList.clear();
	gVarSetList.clear();
	gVarGetList.clear();
	gVarList_Phys.clear();

	const auto& v = Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation::getInstance()->Get_readxml()->getGlobalVarList();
	std::unordered_map<std::string, std::reference_wrapper<decltype(gVarIgnitionState)>> m{
		{"gVarIgnitionState",gVarIgnitionState},{"gVarSetWuP",gVarSetWuP},{"gVarAlternativeTiming",gVarAlternativeTiming},
		{"gVarAlternativeTimingEth1",gVarAlternativeTimingEth1},{"gVarAlternativeTimingEth2",gVarAlternativeTimingEth2},
		{"gVarFcCounterValueSetAll",gVarFcCounterValueSetAll},{"gVarSaveFreshnessAll",gVarSaveFreshnessAll},
		{"gVarService3163Rcvd",gVarService3163Rcvd},{"gVarService3164Rcvd",gVarService3164Rcvd},{"gVarSetFreshnessAll",gVarSetFreshnessAll}
	};
	auto mk = [](const auto& s) { auto p = std::make_shared<IdValuePair<double>>(); p->Id = s.set; p->Name = s.label; p->Length = s.length; return p; };

	for (const auto& s : v) {
		gVarSetList[s.label] = s.set; gVarLengthList[s.label] = s.length; gVarGetList[s.label] = s.get;
		if (auto it = m.find(s.label); it != m.end()) it->second.get().setAddress(s.set);
		gVarList_Phys[s.label] = mk(s);
	}
}