/******************************************************************/
/* FILE: CCHIL.Star.FC3_CardHandling
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#pragma once

#include "Base/FC3_CardHandlingBase.h"
#include "Global/Global.h"
#include <ModelCore/Quantity/Units/Time.h>
#include <ModelCore/Quantity/NumericQuantity.h>
#include "TaskMeasure_HiL/TaskMeasure_HiL.h"
#include "FC3_FileUtilities.h"

namespace CCHIL
{
	namespace Star
	{
		static model_core::quantity::NumericQuantity<double, model_core::quantity::time::Second> timeSinceLastSending = 0.0_s;
		class DLL_EXPORT_COMPONENT FC3_CardHandlingCore : public ::CCHIL::Star::FC3_CardHandlingBase
		{
		public:
			std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_Base::PC_HW_Int_Base> _pc_hw_interface = nullptr;
			//Light
			std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::Light::PC_HW_Int_Light::PC_HW_Int_Light> _pc_hw_interface_light = nullptr;
			uint32_t cardNumber;
			t_hw_com_light_version libVersion = {};

		protected:
			Plugins::HiL::TaskMeasure_HiL::TaskMeasure_HiL _taskMeasurement{ "CCHIL::Star::FC_CardHandlingCore::FC_CardHandlingCore" };
			Plugins::Global::Global globalPlugin;
		private:

			void initialize();
			void uninitialize();

			DEFINE_COMPONENT_CORE_IMPLEMENTATION(FC3_CardHandling)

		}; // END OF CLASS: FC3_CardHandling
	} // END OF NAMESPACE: Star
} // END OF NAMESPACE: CCHIL
