/******************************************************************/
/* FILE: CCHIL.Star.FC3_CardHandling
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#include "FC3_CardHandlingCore.h"



void CCHIL::Star::FC3_CardHandlingCore::FC3_CardHandlingCore::initialize()
{
	cardNumber = 1;
}

void CCHIL::Star::FC3_CardHandlingCore::FC3_CardHandlingCore::uninitialize()
{
}