
/******************************************************************/
/* FILE: CCHIL.Star.FC3_CardHandling
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#pragma once

#include "FC3_CardHandlingCore.h"
#include "ModelCore/Common/Time/SimulationTime.h"

namespace CCHIL
{
    namespace Star
    {
        class DLL_EXPORT_COMPONENT FC3_CardHandling : public ::CCHIL::Star::FC3_CardHandlingCore
        {
        public:	// Local processes
        
        	/// <summary>
        	/// ToDo: doc
        	/// Process:		P102
        	/// Task:			Init
        	///	Priority:		init_P102
        	/// </summary>
        	void P102(::model_core::common::time::SimulationTime* time_info);
        
        	/// <summary>
        	/// ToDo: doc
        	/// Process:		P205
        	/// Task:			Receive
        	///	Priority:		receive_P205
        	/// </summary>
        	void P205(::model_core::common::time::SimulationTime* time_info);
        
        	/// <summary>
        	/// ToDo: doc
        	/// Process:		P405
        	/// Task:			Exit
        	///	Priority:		exit_P405
        	/// </summary>
        	void P405(::model_core::common::time::SimulationTime* time_info);
        
        public: // Common methods
        
        	/*! \copydoc */
        	void register_processes() override;
        	
        
        	/*! \copydoc */
        	void register_signal_connections() override;
        
        
        public:	// Constructors
        
        	/*! \brief Constructor. 
        	 *
        	 *  The component can be used as:
        	 *    - CCHIL.Star.FC3_CardHandling
        	*/
        	explicit FC3_CardHandling(const ::std::vector<::std::string> labels);
        			   	
        	/*! \brief Destructor. */
        	virtual ~FC3_CardHandling();
        }; // END OF CLASS: FC3_CardHandling
    } // END OF NAMESPACE: Star
} // END OF NAMESPACE: CCHIL
