/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#pragma once
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include <cstring>
#include <algorithm>
#include <cstdint>

#include "Global/Global.h"
#include "Base/MG_GM_BEV3_205_9p9_V01_MBase.h"
#include <ETH_Manipulation/ETH_Manipulation.h>
#include "XmlSignalReader/XmlSignalReader.h"
#include "YRS_Transformation/YRS_Transformation.h"
#include "PC_HW_Int_Light/PC_HW_Int_Light.h"

//conditional include for SHA256 calculation
#if defined(_WIN32) || defined(_WIN64) 
    #include <openssl/evp.h>
#else // HiL
    #include <openssl/evp.h>
#endif
// Alias for compact usage
namespace HwLight = Plugins::FlexCard3::PC_HW_Interface::Light;

namespace EID
{
    namespace Net
    {
        namespace ETH
        {
            namespace GM_BEV3_205_9p9_V01_M
            {
                class DLL_EXPORT_COMPONENT MG_GM_BEV3_205_9p9_V01_MCore
                    : public ::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MBase
                {
                public:
                    std::string BusName = "";
                    uint32_t cardNumber = 1;
                    u08 wait = 0;
                    bool success;

                    HwLight::HwComDataObject<void, 0> read_Index{ 0 };
                    uint16_t readSlot_Index = 0;

                    // Global Variable HwComDataObjects (address set from XML)
                    HwLight::HwComDataObject<uint8_t, 1> gVarAlternativeTiming{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarAlternativeTimingEth1{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarAlternativeTimingEth2{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarFcCounterValueSetAll{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarIgnitionState{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarSaveFreshnessAll{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarService3163Rcvd{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarService3164Rcvd{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarSetFreshnessAll{ 0 };
                    HwLight::HwComDataObject<uint8_t, 1> gVarSetWuP{ 0 };


                    // Reset PDU buffers
                    t_hw_com_light_value ResetReceiveBuffer_0[2] = {};
                    t_hw_com_light_value ResetReceiveBuffer_1[2] = {};
                    t_hw_com_light_value ResetReceiveBuffer_2[2] = {};
                    t_hw_com_light_value ResetReceiveBuffer_3[2] = {};

                    // Raw PDU buffers
                    std::vector<uint8_t> GetRawPduHBBuffer_ETH1 = {
                        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
                    };
                    std::vector<uint8_t> GetRawPduInfoBuffer_ETH1 = {
                        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
                    };
                    std::vector<uint8_t> GetRawPduHBBuffer_ETH2 = {
                        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
                    };
                    std::vector<uint8_t> GetRawPduInfoBuffer_ETH2 = {
                        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
                    };

                    // Interfaces
                    std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_Base::PC_HW_Int_Base> pc_hw_int = nullptr;
                    std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_V100::PC_HW_Int_V100> pc_hw_interface = nullptr;
                    std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::Light::PC_HW_Int_Light::PC_HW_Int_Light> pc_hw_interface_light = nullptr;

                    std::map<std::string, SignalDataProcessing::GlobalVar> GlobalVar_list;

                    void InitializeAllLists();
                    void GlobalVars_list();

                    std::map<std::string, unsigned int> gVarLengthList;
                    std::map<std::string, unsigned int> gVarSetList;
                    std::map<std::string, unsigned int> gVarGetList;

                protected:
                    Plugins::Global::Global globalPlugin;
                    Plugins::YRS_Transformation::YRS_Transformation YrsTransformation;
                    Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation* helper =
                        Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation::getInstance();
                    double cycleTimer;

                    std::map<std::string, SignalDataProcessing::Signal> send_gVarList;
                    std::map<std::string, std::shared_ptr<IdValuePair<double>>> gVarList_Phys;

                private:
                    void initialize();
                    void uninitialize();

                    DEFINE_COMPONENT_CORE_IMPLEMENTATION(MG_GM_BEV3_205_9p9_V01_M)

                        std::shared_ptr<Plugins::FlexCard3::XmlSignalReader::XmlSignalReader> BusId_reder = nullptr;
                };
            } // namespace GM_BEV3_205_9p9_V01_M
        } // namespace ETH
    } // namespace Net
} // namespace EID