
/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include "MG_GM_BEV3_205_9p9_V01_M.h"
#include <g3log/g3log.hpp>
#include "ModelCore/Common/Async/WaitHandle.h"
#include "ModelCore/ExecutionEngine/Task.h"
#include "ModelCore/ExecutionEngine/Priority.h"
#include "ModelCore/ExecutionEngine/PriorityQuery.h"
#include "ModelCore/ExecutionEngine/Services/SchedulerService.h"

EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_M(const ::std::vector<::std::string> labels) :
		::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MCore(labels)
{
}

EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_M::~MG_GM_BEV3_205_9p9_V01_M()
{
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_M::register_processes()
{
	Ethernet::register_processes();
	const auto scheduler_service = ::model_core::common::service::find_service<::model_core::execution_engine::services::SchedulerService>();

	// Register: P100 with priority 'init_P100' at task 'Init'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Init", "init_P100");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M),"
			<< " Task: 'Init',"
			<< " Priority: 'init_P100',"
			<< " Process: 'P100'";
		priority->create_action(
			this->get_module_path() +  "->P100", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P100(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P100" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P190 with priority 'init_P190' at task 'Init'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Init", "init_P190");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M),"
			<< " Task: 'Init',"
			<< " Priority: 'init_P190',"
			<< " Process: 'P190'";
		priority->create_action(
			this->get_module_path() +  "->P190", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P190(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P190" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P205 with priority 'receive_P205' at task 'Receive'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Receive", "receive_P205");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M),"
			<< " Task: 'Receive',"
			<< " Priority: 'receive_P205',"
			<< " Process: 'P205'";
		priority->create_action(
			this->get_module_path() +  "->P205", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P205(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P205" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P400 with priority 'exit_P400' at task 'Exit'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Exit", "exit_P400");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M),"
			<< " Task: 'Exit',"
			<< " Priority: 'exit_P400',"
			<< " Process: 'P400'";
		priority->create_action(
			this->get_module_path() +  "->P400", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P400(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P400" << ": " << e.what();
					throw e;
				}
			});
	}
}
void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_M::register_signal_connections()
{
#ifndef IGNORE_DEFAULT_SIGNAL_SYNC
#else
	::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MCore::register_signal_connections();
#endif
}
