
/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#pragma once

#include "MG_GM_BEV3_205_9p9_V01_MCore.h"
#include "ModelCore/Common/Time/SimulationTime.h"

namespace EID
{
    namespace Net
    {
        namespace ETH
        {
            namespace GM_BEV3_205_9p9_V01_M
            {
                class DLL_EXPORT_COMPONENT MG_GM_BEV3_205_9p9_V01_M : public ::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MCore
                {
                public:	// Local processes
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P100
                	/// Task:			Init
                	///	Priority:		init_P100
                	/// </summary>
                	void P100(::model_core::common::time::SimulationTime* time_info);
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P190
                	/// Task:			Init
                	///	Priority:		init_P190
                	/// </summary>
                	void P190(::model_core::common::time::SimulationTime* time_info);
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P205
                	/// Task:			Receive
                	///	Priority:		receive_P205
                	/// </summary>
                	void P205(::model_core::common::time::SimulationTime* time_info);
                
                	/// <summary>
                	/// ToDo: doc
                	/// Process:		P400
                	/// Task:			Exit
                	///	Priority:		exit_P400
                	/// </summary>
                	void P400(::model_core::common::time::SimulationTime* time_info);
                
                public: // Common methods
                
                	/*! \copydoc */
                	void register_processes() override;
                	
                
                	/*! \copydoc */
                	void register_signal_connections() override;
                
                
                public:	// Constructors
                
                	/*! \brief Constructor. 
                	 *
                	 *  The component can be used as:
                	 *    - EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M
                	 *    - EID.Net.ETH.Ethernet
                	*/
                	explicit MG_GM_BEV3_205_9p9_V01_M(const ::std::vector<::std::string> labels);
                			   	
                	/*! \brief Destructor. */
                	virtual ~MG_GM_BEV3_205_9p9_V01_M();
                }; // END OF CLASS: MG_GM_BEV3_205_9p9_V01_M
            } // END OF NAMESPACE: GM_BEV3_205_9p9_V01_M
        } // END OF NAMESPACE: ETH
    } // END OF NAMESPACE: Net
} // END OF NAMESPACE: EID
