/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.MG_GM_BEV3_205_9p9_V01_M
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#include "MG_GM_BEV3_205_9p9_V01_MCore.h"

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MCore::initialize()
{
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MCore::uninitialize()
{
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MCore::InitializeAllLists()
{
    pc_hw_int = PC_HW_Int_Client->getPcHwIntLibVersion();
    pc_hw_interface_light = PC_HW_Int_Lt_Client->getPcHwIntLightVersion();

    GlobalVars_list();
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::MG_GM_BEV3_205_9p9_V01_MCore::GlobalVars_list()
{
    const auto& v = Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation::getInstance()->Get_readxml()->getGlobalVarList();
    std::unordered_map<std::string, std::reference_wrapper<decltype(gVarIgnitionState)>> m{
        {"gVarIgnitionState",gVarIgnitionState},{"gVarSetWuP",gVarSetWuP},{"gVarAlternativeTiming",gVarAlternativeTiming},
        {"gVarAlternativeTimingEth1",gVarAlternativeTimingEth1},{"gVarAlternativeTimingEth2",gVarAlternativeTimingEth2},
        {"gVarFcCounterValueSetAll",gVarFcCounterValueSetAll},{"gVarSaveFreshnessAll",gVarSaveFreshnessAll},
        {"gVarService3163Rcvd",gVarService3163Rcvd},{"gVarService3164Rcvd",gVarService3164Rcvd},{"gVarSetFreshnessAll",gVarSetFreshnessAll}
    };
    auto mk = [](const auto& s) { auto p = std::make_shared<IdValuePair<double>>(); p->Id = s.set; p->Name = s.label; p->Length = s.length; return p; };

    for (const auto& s : v) {
        gVarSetList[s.label] = s.set; gVarLengthList[s.label] = s.length; gVarGetList[s.label] = s.get;
        if (auto it = m.find(s.label); it != m.end()) it->second.get().setAddress(s.set);
        gVarList_Phys[s.label] = mk(s);
    }
}