
/******************************************************************/
/* FILE: CCHIL.Star.FC3_CardHandling
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#pragma once

#include <initializer_list>
#include <string>
#include "ModelCore/Platform.h"

// Registration of module CCHIL.Star.FC3_CardHandling
// Component:  CCHIL::Star::FC3_CardHandling
extern "C"
{
	DLL_EXPORT_COMPONENT void register_component();
	DLL_EXPORT_COMPONENT void register_component_with_labels(::std::initializer_list<::std::string> labels);
	DLL_EXPORT_COMPONENT void unregister_component();
}