
/******************************************************************/
/* FILE: CCHIL.Star.FC3_CardHandling
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include "Module.h"
#include "FC3_CardHandling.h"
#include "ModelCore/Model/Services/ComponentService.h"
#include <g3log/g3log.hpp>

static ::std::vector<CCHIL::Star::FC3_CardHandling*> _cchil_star_fc3_cardhandling_component_handles;


bool check_duplicate_registration(const ::std::string label)
{
	const auto component = model_core::common::service::find_service<model_core::model::services::ComponentService>()->get_component(::std::string(label));

	if (component != nullptr) {
		LOG(G3LOG_DEBUG) << "skip registration:" << label;
		return true;
	}

	return false;
}

void register_component()
{
	if (check_duplicate_registration("CCHIL.Star.FC3_CardHandling"))
		return;

	LOG(G3LOG_DEBUG) << "Register module. CCHIL.Star.FC3_CardHandling";
	auto handle = new CCHIL::Star::FC3_CardHandling({"CCHIL.Star.FC3_CardHandling"});
	_cchil_star_fc3_cardhandling_component_handles.push_back(handle);
	model_core::common::service::find_service<model_core::model::services::ComponentService>()->register_component(handle);

}

void unregister_component()
{
	LOG(G3LOG_DEBUG) << "Unregister module. CCHIL.Star.FC3_CardHandling";	
	for (const auto handle : _cchil_star_fc3_cardhandling_component_handles)
	{
		model_core::common::service::find_service<model_core::model::services::ComponentService>()->unregister_component(handle);
		delete handle;
	}
	_cchil_star_fc3_cardhandling_component_handles.clear();
}

void register_component_with_labels(const ::std::initializer_list<::std::string> labels)
{
	LOG(G3LOG_DEBUG) << "Register module with labels. CCHIL.Star.FC3_CardHandling";
	for (auto label : labels)
	{
		if (check_duplicate_registration(label))
			continue;

		LOG(G3LOG_DEBUG) << "\t *" << label;
		auto handle = new CCHIL::Star::FC3_CardHandling({label, "CCHIL.Star.FC3_CardHandling"});
		_cchil_star_fc3_cardhandling_component_handles.push_back(handle);
		model_core::common::service::find_service<model_core::model::services::ComponentService>()->register_component(handle);
	}


}