
/******************************************************************/
/* FILE: Kernel.FL3X.RBSGeneral_HiL
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include "RBSGeneral_HiL.h"
#include <g3log/g3log.hpp>
#include "ModelCore/Common/Async/WaitHandle.h"
#include "ModelCore/ExecutionEngine/Task.h"
#include "ModelCore/ExecutionEngine/Priority.h"
#include "ModelCore/ExecutionEngine/PriorityQuery.h"
#include "ModelCore/ExecutionEngine/Services/SchedulerService.h"

Kernel::FL3X::RBSGeneral_HiL::RBSGeneral_HiL(const ::std::vector<::std::string> labels) :
		::Kernel::FL3X::RBSGeneral_HiLCore(labels)
{
}

Kernel::FL3X::RBSGeneral_HiL::~RBSGeneral_HiL()
{
}

void Kernel::FL3X::RBSGeneral_HiL::register_processes()
{
	RBSGeneral::register_processes();
	const auto scheduler_service = ::model_core::common::service::find_service<::model_core::execution_engine::services::SchedulerService>();

	// Register: P205 with priority 'receive_P205' at task 'Receive'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Receive", "receive_P205");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (Kernel.FL3X.RBSGeneral_HiL),"
			<< " Task: 'Receive',"
			<< " Priority: 'receive_P205',"
			<< " Process: 'P205'";
		priority->create_action(
			this->get_module_path() +  "->P205", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P205(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P205" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P380 with priority 'send_P380' at task 'Send'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Send", "send_P380");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (Kernel.FL3X.RBSGeneral_HiL),"
			<< " Task: 'Send',"
			<< " Priority: 'send_P380',"
			<< " Process: 'P380'";
		priority->create_action(
			this->get_module_path() +  "->P380", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P380(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P380" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P110 with priority 'init_P110' at task 'Init'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Init", "init_P110");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (Kernel.FL3X.RBSGeneral_HiL),"
			<< " Task: 'Init',"
			<< " Priority: 'init_P110',"
			<< " Process: 'P110'";
		priority->create_action(
			this->get_module_path() +  "->P110", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P110(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P110" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P405 with priority 'exit_P405' at task 'Exit'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Exit", "exit_P405");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (Kernel.FL3X.RBSGeneral_HiL),"
			<< " Task: 'Exit',"
			<< " Priority: 'exit_P405',"
			<< " Process: 'P405'";
		priority->create_action(
			this->get_module_path() +  "->P405", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P405(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P405" << ": " << e.what();
					throw e;
				}
			});
	}
}
void Kernel::FL3X::RBSGeneral_HiL::register_signal_connections()
{
#ifndef IGNORE_DEFAULT_SIGNAL_SYNC
#else
	::Kernel::FL3X::RBSGeneral_HiLCore::register_signal_connections();
#endif
}
