/******************************************************************/
/* FILE: Kernel.FL3X.RBSGeneral_HiL
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#pragma once

#include "Base/RBSGeneral_HiLBase.h"
#include "TaskMeasure_HiL/TaskMeasure_HiL.h"
#include "TestBenchManager/TestBenchManagerAccess.h"
#include "TestBenchManager/TestBenchManager.h"

using namespace model_core::model_access;
namespace HwLight = Plugins::FlexCard3::PC_HW_Interface::Light;

namespace Kernel
{
    namespace FL3X
    {
        class DLL_EXPORT_COMPONENT RBSGeneral_HiLCore : public ::Kernel::FL3X::RBSGeneral_HiLBase
        {
        protected:
            // Standard Interface
            //std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_Base::PC_HW_Int_Base> pc_hw_int = nullptr;
            //std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_V100::PC_HW_Int_V100> pc_hw_interface = nullptr;
            //Light interface for FlexCard3
            std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::Light::PC_HW_Int_Light::PC_HW_Int_Light> pc_hw_interface_light = nullptr;

            Plugins::HiL::TaskMeasure_HiL::TaskMeasure_HiL _taskMeasurement{ "Kernel::FL3X::RBSGeneral_HiLCore::RBSGeneral_HiLCore" };
            Plugins::HiL::TaskMeasure_HiL::TaskMeasure_HiL _taskMeasurement380{ "Kernel::FL3X::RBSGeneral_HiLCore::RBSGeneral_HiLCore" };

        private:

            void initialize();
            void uninitialize();

        public:
            Plugins::HiL::TestBenchManager::TestBenchManagerAccess _testbench_manager_access;
            shared_ptr<Plugins::HiL::TestBenchManager::TestBenchManager> _testbench_manager;

            bool success;
            uint32_t cardNumber = 1;
            u08 wait = 0;

            HwLight::HwComDataObject<void, 0> read_Index{ 0 };
            uint16_t readSlot_Index = 0;
            uint16_t P205readSlot_Index = 0;

            DEFINE_COMPONENT_CORE_IMPLEMENTATION(RBSGeneral_HiL)

        }; // END OF CLASS: RBSGeneral_HiL
    } // END OF NAMESPACE: FL3X
} // END OF NAMESPACE: Kernel