
/******************************************************************/
/* FILE: Kernel.FL3X.RBSGeneral_HiL
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#pragma once

#include "RBSGeneral_HiLCore.h"
#include "ModelCore/Common/Time/SimulationTime.h"

namespace Kernel
{
    namespace FL3X
    {
        class DLL_EXPORT_COMPONENT RBSGeneral_HiL : public ::Kernel::FL3X::RBSGeneral_HiLCore
        {
        public:	// Local processes
        
        	/// <summary>
        	/// ToDo: doc
        	/// Process:		P205
        	/// Task:			Receive
        	///	Priority:		receive_P205
        	/// </summary>
        	void P205(::model_core::common::time::SimulationTime* time_info);
        
        	/// <summary>
        	/// ToDo: doc
        	/// Process:		P380
        	/// Task:			Send
        	///	Priority:		send_P380
        	/// </summary>
        	void P380(::model_core::common::time::SimulationTime* time_info);
        
        	/// <summary>
        	/// ToDo: doc
        	/// Process:		P110
        	/// Task:			Init
        	///	Priority:		init_P110
        	/// </summary>
        	void P110(::model_core::common::time::SimulationTime* time_info);
        
        	/// <summary>
        	/// ToDo: doc
        	/// Process:		P405
        	/// Task:			Exit
        	///	Priority:		exit_P405
        	/// </summary>
        	void P405(::model_core::common::time::SimulationTime* time_info);
        
        public: // Common methods
        
        	/*! \copydoc */
        	void register_processes() override;
        	
        
        	/*! \copydoc */
        	void register_signal_connections() override;
        
        
        public:	// Constructors
        
        	/*! \brief Constructor. 
        	 *
        	 *  The component can be used as:
        	 *    - Kernel.FL3X.RBSGeneral_HiL
        	 *    - Kernel.FL3X.RBSGeneral
        	*/
        	explicit RBSGeneral_HiL(const ::std::vector<::std::string> labels);
        			   	
        	/*! \brief Destructor. */
        	virtual ~RBSGeneral_HiL();
        }; // END OF CLASS: RBSGeneral_HiL
    } // END OF NAMESPACE: FL3X
} // END OF NAMESPACE: Kernel
