/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.Receive
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#pragma once

#include "Base/ReceiveBase.h"
#include "Global/Global.h"

#include "XmlSignalReader/XmlSignalReader.h"
#include "Defs/ModelData.h"
#include "Defs/ManipHelperClass.h"
#include <vector>
#include "Global/macros.h"

using namespace model_core::model_access;
namespace HwLight = Plugins::FlexCard3::PC_HW_Interface::Light;
namespace HwSerializer = Plugins::FlexCard3::PC_HW_Interface::Light::HwSerializer;

namespace EID
{
	namespace Net
	{
		namespace ETH
		{
			namespace GM_BEV3_205_9p9_V01_M
			{
				class DLL_EXPORT_COMPONENT ReceiveCore : public ::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveBase
				{
				public:
					const std::string STAR_PREFIX{ "FC3: " };
					u08 wait = 0;
					bool success;


					//Receive PDUs HwComDataObjects
					//ETH1 Receive 
					HwLight::HwComDataObject<void, 36> Receive_ETH1_PDU_WuP{ 0 };
					HwLight::HwComDataObject<void, 18> Receive_ETH1_PDU_Heartbeat{ 0 };
					HwLight::HwComDataObject<void, 29> Receive_ETH1_PDU_Info{ 0 };

					// ETH2 Receive
					HwLight::HwComDataObject<void, 36> Receive_ETH2_PDU_WuP{ 0 };
					HwLight::HwComDataObject<void, 18> Receive_ETH2_PDU_Heartbeat{ 0 };
					HwLight::HwComDataObject<void, 29> Receive_ETH2_PDU_Info{ 0 };
					
					//Receuve Signals HwComDataObjects
					//ETH Receive UInt 8
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBst_BstWthWarningP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBst_BstWthWarningS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBC_AchvdInvP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBC_AchvdInvS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActCurr1FA_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActCurr1FA_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActCurr2FA_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActCurr2FA_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActVolt1FA_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActVolt1FA_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActVolt2FA_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstBrkActVolt2FA_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstDgrdDBRReqstdP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstDgrdDBRReqstdS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstLeakModeActvP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstLeakModeActvS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstMC_AchvdInvP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstMC_AchvdInvS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstPCanCommStsP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstPCanCommStsS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstPwrMgmtActP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstPwrMgmtActS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstRecoveryActvP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstRecoveryActvS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_InvRrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_eBstWS_StndStllRrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_MIL_ReqFromEBCM_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_b_MIL_ReqFromEBCM_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_YeBACR_b_eBst_BstUnavlblP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_YeBACR_b_eBst_BstUnavlblS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint8_t, sizeof(uint8_t)> receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRrS__Sig_Signal{ 0 };

					//ETH Receive UInt 16
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_PulsRrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD1_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD2_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD3_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD4_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD5_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD6_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD7_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_LfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_LfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_LrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_LrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_RfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_RfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_RrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_Cnt_eBstWS_TmD8_RrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstEBCM_SwVerAlphP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstEBCM_SwVerAlphS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstPwrMgmtRsnP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstPwrMgmtRsnS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint16_t, sizeof(uint16_t)> receive_eth_VeBACR_d_eBstWS_VdaBitsRrS__Sig_Signal{ 0 };

					//ETH Receive UInt 32
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_Cnt_eBstWS_TmRrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_g_eBstEBCM_SwVerPN_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<uint32_t, sizeof(uint32_t)> receive_eth_VeBACR_g_eBstEBCM_SwVerPN_S__Sig_Signal{ 0 };

					//ETH Receive Int 16
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_AchModeLtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_AchModeLtS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_AchModeRtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_AchModeRtS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_StateLtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_StateLtS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_StateRtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstEPB_StateRtS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstFluidLvlRawP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstFluidLvlRawS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstHydFuncStP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstHydFuncStS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstIntrSelfTstStsP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstIntrSelfTstStsS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstMC_StsP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstMC_StsS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstPlngrPosnStsP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstPlngrPosnStsS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstRplnshStsP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstRplnshStsS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstVDA_PbcHPO_ReqP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstVDA_PbcHPO_ReqS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_eBstWhlCntrlStsRrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_SbmPrimDiagStStsP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_VeBACR_e_SbmPrimDiagStStsS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_YeBACR_e_eBstEBOS_EBCMStateP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_YeBACR_e_eBstEBOS_EBCMStateS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_YeBACR_e_eBstEPB_StatusLtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_YeBACR_e_eBstEPB_StatusLtS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_YeBACR_e_eBstEPB_StatusRtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<int16_t, sizeof(int16_t)> receive_eth_YeBACR_e_eBstEPB_StatusRtS__Sig_Signal{ 0 };

					//ETH Receive Float
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_F_eBstEPB_AchvdLtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_F_eBstEPB_AchvdLtS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_F_eBstEPB_AchvdRtP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_F_eBstEPB_AchvdRtS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_I_eBstBrkActCurr1_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_I_eBstBrkActCurr1_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_I_eBstBrkActCurr2_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_I_eBstBrkActCurr2_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_U_eBstBrkActVolt1_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_U_eBstBrkActVolt1_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_U_eBstBrkActVolt2_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_U_eBstBrkActVolt2_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_V_eBstHydCmpOffstVolP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_V_eBstHydCmpOffstVolS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_V_eBstPotPlngrVolP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_V_eBstPotPlngrVolS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_V_eBstRemPlngrVolP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_V_eBstRemPlngrVolS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_l_eBstMCP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_l_eBstMCS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_l_eBstPlngrPosnP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_l_eBstPlngrPosnS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBC_AchvdP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBC_AchvdS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstLfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstLfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstLrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstLrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstRfP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstRfS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstRrP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstBkPrsEstRrS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstMC_AchvdP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstMC_AchvdS__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstVDA_PbcHPO_P__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_VeBACR_p_eBstVDA_PbcHPO_S__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_YeBACR_Pct_eBstThermalCapP__Sig_Signal{ 0 };
					HwLight::HwComDataObject<float, sizeof(float)> receive_eth_YeBACR_Pct_eBstThermalCapS__Sig_Signal{ 0 };

					// Generic processing helpers
					std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_b_eBst_BstWthWarningP__Sig_Signal)>> receiveHwU8SignalMap;
					std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_Cnt_eBstWS_PulsLfP__Sig_Signal)>> receiveHwU16SignalMap;
					std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_Cnt_eBstWS_TmLfP__Sig_Signal)>> receiveHwU32SignalMap;
					std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_e_eBstEPB_AchModeLtP__Sig_Signal)>> receiveHwI16SignalMap;
					std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_F_eBstEPB_AchvdLtP__Sig_Signal)>> receiveHwFloatSignalMap;

					std::unordered_map<std::string, double> receiveOldPhysValueMap;

					std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_Base::PC_HW_Int_Base> pc_hw_int = nullptr;
					std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::PC_HW_Int_V100::PC_HW_Int_V100> pc_hw_interface = nullptr;
					//Light
					std::shared_ptr<Plugins::FlexCard3::PC_HW_Interface::Light::PC_HW_Int_Light::PC_HW_Int_Light> pc_hw_interface_light = nullptr;
					std::string nodeName = "";  // NOLINT(readability-redundant-string-init)
					uint32_t cardNumber = 1;
					Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation* helper = Plugins::FlexCard3::ETH_Manipulation::ETH_Manipulation::getInstance();
					
					t_hw_com_light_value value_to_get[4];
					std::vector<double> idBuffer;
					
					std::vector<t_hw_com_light_value> local_get_data;
					std::vector<std::array<uint8_t, 8>> buffers;
					std::vector<std::string> labels;

					static constexpr size_t total_signals = 202;
					static constexpr size_t max_per_buffer = 75;

					// Buffers for each hardware call (size may vary for the last batch)
					std::vector<t_hw_com_light_value> value_to_get_data_0;
					std::vector<t_hw_com_light_value> value_to_get_data_1;
					std::vector<t_hw_com_light_value> value_to_get_data_2;

					// Track how many signals each batch actually has
					uint16_t count0 = 0, count1 = 0, count2 = 0;

					//PDU list
					std::map<std::string, unsigned int> PDUManipList;
					std::map<std::string, unsigned int> PDULengthList;
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> PDUSetList;//This has name and ID,value of float type
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> PDUGetList;//This has name and ID,value of float type
					std::map<std::string, SignalDataProcessing::PDU> sendPDUList;
					std::map<std::string, SignalDataProcessing::PDU> receivePDUList;

					void PDUListData();

					t_hw_com_light_value ResetReceiveBuffer_0[2] = {};
					t_hw_com_light_value ResetReceiveBuffer_1[2] = {};
					t_hw_com_light_value ResetReceiveBuffer_2[2] = {};
					t_hw_com_light_value ResetReceiveBuffer_3[2] = {};

					//ETH1 PDUs
					const std::string ETH1_WakeUp_PDU = "PDU_SYS_PMUnicastTxMechatronicsT1S_Wakeup";
					const std::string ETH1_HeartBeat_PDU = "PDU_SYS_PMMulticastTxMechatronicsT1S_Heartbeat";
					const std::string ETH1_Info_PDU = "PDU_SYS_SMUnicastTxMechatronicsT1S_Info";
					
					//ETH2 PDUs
					const std::string ETH2_WakeUp_PDU = "PDU_SYS_PMUnicastTxMechatronicsT1S_Eth2_Wakeup";
					const std::string ETH2_HeartBeat_PDU = "PDU_SYS_PMMulticastTxMechatronicsT1S_Eth2_Heartbeat";
					const std::string ETH2_Info_PDU = "PDU_SYS_SMUnicastTxMechatronicsT1S_Eth2_Info";

				protected:

					Plugins::Global::Global globalPlugin;
					double cycleTimer;
					double cycleTimer_ReceiveSignalCount;
					double cycleTimerETH1_ReceivePDUCount;
					double cycleTimerETH2_ReceivePDUCount;
					//Info
					double cycleTimer_Receive_ETH1_InfoPDUCount;
					double cycleTimer_Receive_ETH2_InfoPDUCount;

					// Persistent buffers for receive operations
					std::vector<uint8_t> m_receiveBuffer_ETH1_HB;
					std::vector<uint8_t> m_receiveBuffer_ETH2_HB;
					std::vector<uint8_t> m_receiveBuffer_ETH1_Info;
					std::vector<uint8_t> m_receiveBuffer_ETH2_Info;
					std::vector<uint8_t> m_receiveBuffer_Signals;
					std::vector<uint8_t> m_receiveBuffer_Signals2;
					std::vector<uint8_t> m_receiveBuffer_Signals3;

					std::map<std::string, model_core::model::Signal*> moduloSignalList;
					std::vector<Defs::ManipulationSignalHelperfloat*> FloatSigManipulationHelperList;

					//Signals Raw list
					std::map<std::string, unsigned int> signalGetRawList;
					std::map<std::string, unsigned int> signalLenRawList;
					//std::map<std::string, unsigned int> signalSetRawList;

					//Signals phys list
					std::map<std::string, unsigned int> signalGetphysList;
					std::map<std::string, unsigned int> signalLenphysList;
					std::map<std::string, unsigned int> signalSetphysList;

					std::map<std::string, SignalDataProcessing::Signal> ReceiveSignalsList_Raw;
					std::map<std::string, SignalDataProcessing::Signal> ReceiveSignalsList_Phys;

					std::map<std::string, std::shared_ptr<IdValuePair<double>>> Receive_Signal_Phys_List;//This has name and ID,value of float type
					std::map<std::string, std::shared_ptr<IdValuePair<double>>> Receive_Signal_Raw_List;//This has name and ID,value of float type

					//Reset Buffer
					std::vector<uint8_t> GetRawPduHBBuffer_ETH1 = {
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00
					};
					std::vector<uint8_t> GetRawPduInfoBuffer_ETH1 = {
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00
					};
					std::vector<uint8_t> GetRawPduHBBuffer_ETH2 = {
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00
					};
					std::vector<uint8_t> GetRawPduInfoBuffer_ETH2 = {
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00
					};

					void InitializeAllLists();
					void GetSignalsListData();

				private:

					void initialize();
					void uninitialize();

					DEFINE_COMPONENT_CORE_IMPLEMENTATION(Receive)

				}; // END OF CLASS: Receive
			} // END OF NAMESPACE: GM_BEV3_205_9p9_V01_M
		} // END OF NAMESPACE: ETH
	} // END OF NAMESPACE: Net
} // END OF NAMESPACE: EID
