
/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.Receive
/* SW-COMPONENT: C++-genericToolChainModelComponent 
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2026 Robert Bosch GmbH 
/*  
/* The reproduction, distribution and utilization of this file as 
/* well as the communication of its contents to others without express 
/* authorization is prohibited. Offenders will be held liable for the 
/* payment of damages. All rights reserved in the event of the grant 
/* of a patent, utility model or design. 
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!                                 !!!
// !!!      DO NOT EDIT THIS FILE      !!!
// !!!                                 !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include "Receive.h"
#include <g3log/g3log.hpp>
#include "ModelCore/Common/Async/WaitHandle.h"
#include "ModelCore/ExecutionEngine/Task.h"
#include "ModelCore/ExecutionEngine/Priority.h"
#include "ModelCore/ExecutionEngine/PriorityQuery.h"
#include "ModelCore/ExecutionEngine/Services/SchedulerService.h"

EID::Net::ETH::GM_BEV3_205_9p9_V01_M::Receive::Receive(const ::std::vector<::std::string> labels) :
		::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveCore(labels)
{
}

EID::Net::ETH::GM_BEV3_205_9p9_V01_M::Receive::~Receive()
{
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::Receive::register_processes()
{
	const auto scheduler_service = ::model_core::common::service::find_service<::model_core::execution_engine::services::SchedulerService>();

	// Register: P195 with priority 'init_P195' at task 'Init'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Init", "init_P195");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.Receive),"
			<< " Task: 'Init',"
			<< " Priority: 'init_P195',"
			<< " Process: 'P195'";
		priority->create_action(
			this->get_module_path() +  "->P195", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P195(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P195" << ": " << e.what();
					throw e;
				}
			});
	}

	// Register: P220 with priority 'receive_P220' at task 'Receive'
	{
		const auto identifier = ::model_core::execution_engine::PriorityQuery("Receive", "receive_P220");
		auto priority = scheduler_service->get_priority(identifier);
		LOG_IF(FATAL, (priority == nullptr)) << "Failed to register process."
			<< " Component: "<< this->get_module_path() << " (EID.Net.ETH.GM_BEV3_205_9p9_V01_M.Receive),"
			<< " Task: 'Receive',"
			<< " Priority: 'receive_P220',"
			<< " Process: 'P220'";
		priority->create_action(
			this->get_module_path() +  "->P220", 
			[=](auto simulation_time) 
			{
				try 
				{
					this->P220(simulation_time);
				}
				catch (const std::exception& e)
				{
					LOG(WARNING) << "Exception in " << this->get_module_path() << "P220" << ": " << e.what();
					throw e;
				}
			});
	}
}
void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::Receive::register_signal_connections()
{
#ifndef IGNORE_DEFAULT_SIGNAL_SYNC
#else
	::EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveCore::register_signal_connections();
#endif
}
