/******************************************************************/
/* FILE: EID.Net.ETH.GM_BEV3_205_9p9_V01_M.Receive
/* SW-COMPONENT: C++-genericToolChainModelComponent
/* DESCRIPTION: Source is used to build a Labcar model component for a generic ToolChain, based on C++ code
/* COPYRIGHT: (C) 2025 Robert Bosch GmbH
/*
/* The reproduction, distribution and utilization of this file as
/* well as the communication of its contents to others without express
/* authorization is prohibited. Offenders will be held liable for the
/* payment of damages. All rights reserved in the event of the grant
/* of a patent, utility model or design.
/******************************************************************/

/******************************************************************/
/* This code was generated by the CCXiL ToolChain
/******************************************************************/

// !!! Use this file to add custom logic to this Component - this file will not be generated again !!!

#include "ReceiveCore.h"
#include "Defs/ModelData.h"

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveCore::ReceiveCore::initialize()
{
	//read Node name
	const std::string moduleName = this->get_component_description().get_module_name();
	const auto found = moduleName.find_last_of('.'); //was "." (Linux?)
	nodeName = moduleName.substr(found + 1);

	moduloSignalList.clear();

	for (::model_core::model::Signal* moduloSignal : this->get_signals())
	{
		moduloSignalList.insert(std::make_pair(moduloSignal->get_name(), moduloSignal));
	}
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveCore::ReceiveCore::uninitialize()
{
	FloatSigManipulationHelperList.clear();
	receiveOldPhysValueMap.clear();
	receiveHwU8SignalMap.clear();
	//receiveHwU16SignalMap.clear();
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveCore::ReceiveCore::InitializeAllLists()
{
	pc_hw_int = PC_HW_Int_Client->getPcHwIntLibVersion();
	pc_hw_interface_light = PC_HW_Int_Lt_Client->getPcHwIntLightVersion();

	PDUListData();
	GetSignalsListData();
	FloatSigManipulationHelperList.clear();
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveCore::ReceiveCore::GetSignalsListData()
{
	auto signals_xml = helper->Get_readxml()->GetSetSignalList(nodeName.c_str());

	std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_b_eBst_BstWthWarningP__Sig_Signal)>> u8Signals
	{
		{"VeBACR_b_eBst_BstWthWarningP", receive_eth_VeBACR_b_eBst_BstWthWarningP__Sig_Signal},
		{"VeBACR_b_eBst_BstWthWarningS", receive_eth_VeBACR_b_eBst_BstWthWarningS__Sig_Signal},
		{"VeBACR_b_eBstBC_AchvdInvP", receive_eth_VeBACR_b_eBstBC_AchvdInvP__Sig_Signal},
		{"VeBACR_b_eBstBC_AchvdInvS", receive_eth_VeBACR_b_eBstBC_AchvdInvS__Sig_Signal},
		{"VeBACR_b_eBstBrkActCurr1FA_P", receive_eth_VeBACR_b_eBstBrkActCurr1FA_P__Sig_Signal},
		{"VeBACR_b_eBstBrkActCurr1FA_S", receive_eth_VeBACR_b_eBstBrkActCurr1FA_S__Sig_Signal},
		{"VeBACR_b_eBstBrkActCurr2FA_P", receive_eth_VeBACR_b_eBstBrkActCurr2FA_P__Sig_Signal},
		{"VeBACR_b_eBstBrkActCurr2FA_S", receive_eth_VeBACR_b_eBstBrkActCurr2FA_S__Sig_Signal},
		{"VeBACR_b_eBstBrkActVolt1FA_P", receive_eth_VeBACR_b_eBstBrkActVolt1FA_P__Sig_Signal},
		{"VeBACR_b_eBstBrkActVolt1FA_S", receive_eth_VeBACR_b_eBstBrkActVolt1FA_S__Sig_Signal},
		{"VeBACR_b_eBstBrkActVolt2FA_P", receive_eth_VeBACR_b_eBstBrkActVolt2FA_P__Sig_Signal},
		{"VeBACR_b_eBstBrkActVolt2FA_S", receive_eth_VeBACR_b_eBstBrkActVolt2FA_S__Sig_Signal},
		{"VeBACR_b_eBstDgrdDBRReqstdP", receive_eth_VeBACR_b_eBstDgrdDBRReqstdP__Sig_Signal},
		{"VeBACR_b_eBstDgrdDBRReqstdS", receive_eth_VeBACR_b_eBstDgrdDBRReqstdS__Sig_Signal},
		{"VeBACR_b_eBstLeakModeActvP", receive_eth_VeBACR_b_eBstLeakModeActvP__Sig_Signal},
		{"VeBACR_b_eBstLeakModeActvS", receive_eth_VeBACR_b_eBstLeakModeActvS__Sig_Signal},
		{"VeBACR_b_eBstMC_AchvdInvP", receive_eth_VeBACR_b_eBstMC_AchvdInvP__Sig_Signal},
		{"VeBACR_b_eBstMC_AchvdInvS", receive_eth_VeBACR_b_eBstMC_AchvdInvS__Sig_Signal},
		{"VeBACR_b_eBstPCanCommStsP", receive_eth_VeBACR_b_eBstPCanCommStsP__Sig_Signal},
		{"VeBACR_b_eBstPCanCommStsS", receive_eth_VeBACR_b_eBstPCanCommStsS__Sig_Signal},
		{"VeBACR_b_eBstPwrMgmtActP", receive_eth_VeBACR_b_eBstPwrMgmtActP__Sig_Signal},
		{"VeBACR_b_eBstPwrMgmtActS", receive_eth_VeBACR_b_eBstPwrMgmtActS__Sig_Signal},
		{"VeBACR_b_eBstRecoveryActvP", receive_eth_VeBACR_b_eBstRecoveryActvP__Sig_Signal},
		{"VeBACR_b_eBstRecoveryActvS", receive_eth_VeBACR_b_eBstRecoveryActvS__Sig_Signal},
		{"VeBACR_b_eBstWS_InvLfP", receive_eth_VeBACR_b_eBstWS_InvLfP__Sig_Signal},
		{"VeBACR_b_eBstWS_InvLfS", receive_eth_VeBACR_b_eBstWS_InvLfS__Sig_Signal},
		{"VeBACR_b_eBstWS_InvLrP", receive_eth_VeBACR_b_eBstWS_InvLrP__Sig_Signal},
		{"VeBACR_b_eBstWS_InvLrS", receive_eth_VeBACR_b_eBstWS_InvLrS__Sig_Signal},
		{"VeBACR_b_eBstWS_InvRfP", receive_eth_VeBACR_b_eBstWS_InvRfP__Sig_Signal},
		{"VeBACR_b_eBstWS_InvRfS", receive_eth_VeBACR_b_eBstWS_InvRfS__Sig_Signal},
		{"VeBACR_b_eBstWS_InvRrP", receive_eth_VeBACR_b_eBstWS_InvRrP__Sig_Signal},
		{"VeBACR_b_eBstWS_InvRrS", receive_eth_VeBACR_b_eBstWS_InvRrS__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllLfP", receive_eth_VeBACR_b_eBstWS_StndStllLfP__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllLfS", receive_eth_VeBACR_b_eBstWS_StndStllLfS__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllLrP", receive_eth_VeBACR_b_eBstWS_StndStllLrP__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllLrS", receive_eth_VeBACR_b_eBstWS_StndStllLrS__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllRfP", receive_eth_VeBACR_b_eBstWS_StndStllRfP__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllRfS", receive_eth_VeBACR_b_eBstWS_StndStllRfS__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllRrP", receive_eth_VeBACR_b_eBstWS_StndStllRrP__Sig_Signal},
		{"VeBACR_b_eBstWS_StndStllRrS", receive_eth_VeBACR_b_eBstWS_StndStllRrS__Sig_Signal},
		{"VeBACR_b_MIL_ReqFromEBCM_P", receive_eth_VeBACR_b_MIL_ReqFromEBCM_P__Sig_Signal},
		{"VeBACR_b_MIL_ReqFromEBCM_S", receive_eth_VeBACR_b_MIL_ReqFromEBCM_S__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsLfP", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsLfS", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsLrP", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsLrS", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsLrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsRfP", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsRfS", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsRrP", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_VdaBitsRrS", receive_eth_VeBACR_Cnt_eBstWS_VdaBitsRrS__Sig_Signal},
		{"YeBACR_b_eBst_BstUnavlblP", receive_eth_YeBACR_b_eBst_BstUnavlblP__Sig_Signal},
		{"YeBACR_b_eBst_BstUnavlblS", receive_eth_YeBACR_b_eBst_BstUnavlblS__Sig_Signal},
	};

	std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_Cnt_eBstWS_PulsLfP__Sig_Signal)>> u16Signals
	{
		{"VeBACR_Cnt_eBstWS_PulsLfP", receive_eth_VeBACR_Cnt_eBstWS_PulsLfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_PulsLfS", receive_eth_VeBACR_Cnt_eBstWS_PulsLfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_PulsLrP", receive_eth_VeBACR_Cnt_eBstWS_PulsLrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_PulsLrS", receive_eth_VeBACR_Cnt_eBstWS_PulsLrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_PulsRfP", receive_eth_VeBACR_Cnt_eBstWS_PulsRfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_PulsRfS", receive_eth_VeBACR_Cnt_eBstWS_PulsRfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_PulsRrP", receive_eth_VeBACR_Cnt_eBstWS_PulsRrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_PulsRrS", receive_eth_VeBACR_Cnt_eBstWS_PulsRrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD1_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD1_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD1_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD1_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD1_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD1_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD1_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD1_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD1_RrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD2_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD2_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD2_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD2_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD2_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD2_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD2_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD2_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD2_RrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD3_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD3_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD3_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD3_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD3_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD3_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD3_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD3_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD3_RrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD4_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD4_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD4_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD4_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD4_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD4_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD4_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD4_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD4_RrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD5_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD5_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD5_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD5_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD5_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD5_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD5_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD5_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD5_RrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD6_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD6_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD6_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD6_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD6_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD6_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD6_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD6_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD6_RrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD7_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD7_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD7_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD7_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD7_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD7_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD7_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD7_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD7_RrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_LfP", receive_eth_VeBACR_Cnt_eBstWS_TmD8_LfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_LfS", receive_eth_VeBACR_Cnt_eBstWS_TmD8_LfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_LrP", receive_eth_VeBACR_Cnt_eBstWS_TmD8_LrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_LrS", receive_eth_VeBACR_Cnt_eBstWS_TmD8_LrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_RfP", receive_eth_VeBACR_Cnt_eBstWS_TmD8_RfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_RfS", receive_eth_VeBACR_Cnt_eBstWS_TmD8_RfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_RrP", receive_eth_VeBACR_Cnt_eBstWS_TmD8_RrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmD8_RrS", receive_eth_VeBACR_Cnt_eBstWS_TmD8_RrS__Sig_Signal},
		{"VeBACR_d_eBstEBCM_SwVerAlphP", receive_eth_VeBACR_d_eBstEBCM_SwVerAlphP__Sig_Signal},
		{"VeBACR_d_eBstEBCM_SwVerAlphS", receive_eth_VeBACR_d_eBstEBCM_SwVerAlphS__Sig_Signal},
		{"VeBACR_d_eBstPwrMgmtRsnP", receive_eth_VeBACR_d_eBstPwrMgmtRsnP__Sig_Signal},
		{"VeBACR_d_eBstPwrMgmtRsnS", receive_eth_VeBACR_d_eBstPwrMgmtRsnS__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsLfP", receive_eth_VeBACR_d_eBstWS_VdaBitsLfP__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsLfS", receive_eth_VeBACR_d_eBstWS_VdaBitsLfS__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsLrP", receive_eth_VeBACR_d_eBstWS_VdaBitsLrP__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsLrS", receive_eth_VeBACR_d_eBstWS_VdaBitsLrS__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsRfP", receive_eth_VeBACR_d_eBstWS_VdaBitsRfP__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsRfS", receive_eth_VeBACR_d_eBstWS_VdaBitsRfS__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsRrP", receive_eth_VeBACR_d_eBstWS_VdaBitsRrP__Sig_Signal},
		{"VeBACR_d_eBstWS_VdaBitsRrS", receive_eth_VeBACR_d_eBstWS_VdaBitsRrS__Sig_Signal},
	};

	std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_Cnt_eBstWS_TmLfP__Sig_Signal)>> u32Signals
	{
		{"VeBACR_Cnt_eBstWS_TmLfP", receive_eth_VeBACR_Cnt_eBstWS_TmLfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmLfS", receive_eth_VeBACR_Cnt_eBstWS_TmLfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmLrP", receive_eth_VeBACR_Cnt_eBstWS_TmLrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmLrS", receive_eth_VeBACR_Cnt_eBstWS_TmLrS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmRfP", receive_eth_VeBACR_Cnt_eBstWS_TmRfP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmRfS", receive_eth_VeBACR_Cnt_eBstWS_TmRfS__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmRrP", receive_eth_VeBACR_Cnt_eBstWS_TmRrP__Sig_Signal},
		{"VeBACR_Cnt_eBstWS_TmRrS", receive_eth_VeBACR_Cnt_eBstWS_TmRrS__Sig_Signal},
		{"VeBACR_g_eBstEBCM_SwVerPN_P", receive_eth_VeBACR_g_eBstEBCM_SwVerPN_P__Sig_Signal},
		{"VeBACR_g_eBstEBCM_SwVerPN_S", receive_eth_VeBACR_g_eBstEBCM_SwVerPN_S__Sig_Signal},
	};

	std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_e_eBstEPB_AchModeLtP__Sig_Signal)>> i16Signals
	{
		{"VeBACR_e_eBstEPB_AchModeLtP", receive_eth_VeBACR_e_eBstEPB_AchModeLtP__Sig_Signal},
		{"VeBACR_e_eBstEPB_AchModeLtS", receive_eth_VeBACR_e_eBstEPB_AchModeLtS__Sig_Signal},
		{"VeBACR_e_eBstEPB_AchModeRtP", receive_eth_VeBACR_e_eBstEPB_AchModeRtP__Sig_Signal},
		{"VeBACR_e_eBstEPB_AchModeRtS", receive_eth_VeBACR_e_eBstEPB_AchModeRtS__Sig_Signal},
		{"VeBACR_e_eBstEPB_StateLtP", receive_eth_VeBACR_e_eBstEPB_StateLtP__Sig_Signal},
		{"VeBACR_e_eBstEPB_StateLtS", receive_eth_VeBACR_e_eBstEPB_StateLtS__Sig_Signal},
		{"VeBACR_e_eBstEPB_StateRtP", receive_eth_VeBACR_e_eBstEPB_StateRtP__Sig_Signal},
		{"VeBACR_e_eBstEPB_StateRtS", receive_eth_VeBACR_e_eBstEPB_StateRtS__Sig_Signal},
		{"VeBACR_e_eBstFluidLvlRawP", receive_eth_VeBACR_e_eBstFluidLvlRawP__Sig_Signal},
		{"VeBACR_e_eBstFluidLvlRawS", receive_eth_VeBACR_e_eBstFluidLvlRawS__Sig_Signal},
		{"VeBACR_e_eBstHydFuncStP", receive_eth_VeBACR_e_eBstHydFuncStP__Sig_Signal},
		{"VeBACR_e_eBstHydFuncStS", receive_eth_VeBACR_e_eBstHydFuncStS__Sig_Signal},
		{"VeBACR_e_eBstIntrSelfTstStsP", receive_eth_VeBACR_e_eBstIntrSelfTstStsP__Sig_Signal},
		{"VeBACR_e_eBstIntrSelfTstStsS", receive_eth_VeBACR_e_eBstIntrSelfTstStsS__Sig_Signal},
		{"VeBACR_e_eBstMC_StsP", receive_eth_VeBACR_e_eBstMC_StsP__Sig_Signal},
		{"VeBACR_e_eBstMC_StsS", receive_eth_VeBACR_e_eBstMC_StsS__Sig_Signal},
		{"VeBACR_e_eBstPlngrPosnStsP", receive_eth_VeBACR_e_eBstPlngrPosnStsP__Sig_Signal},
		{"VeBACR_e_eBstPlngrPosnStsS", receive_eth_VeBACR_e_eBstPlngrPosnStsS__Sig_Signal},
		{"VeBACR_e_eBstRplnshStsP", receive_eth_VeBACR_e_eBstRplnshStsP__Sig_Signal},
		{"VeBACR_e_eBstRplnshStsS", receive_eth_VeBACR_e_eBstRplnshStsS__Sig_Signal},
		{"VeBACR_e_eBstVDA_PbcHPO_ReqP", receive_eth_VeBACR_e_eBstVDA_PbcHPO_ReqP__Sig_Signal},
		{"VeBACR_e_eBstVDA_PbcHPO_ReqS", receive_eth_VeBACR_e_eBstVDA_PbcHPO_ReqS__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsLfP", receive_eth_VeBACR_e_eBstWhlCntrlStsLfP__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsLfS", receive_eth_VeBACR_e_eBstWhlCntrlStsLfS__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsLrP", receive_eth_VeBACR_e_eBstWhlCntrlStsLrP__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsLrS", receive_eth_VeBACR_e_eBstWhlCntrlStsLrS__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsRfP", receive_eth_VeBACR_e_eBstWhlCntrlStsRfP__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsRfS", receive_eth_VeBACR_e_eBstWhlCntrlStsRfS__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsRrP", receive_eth_VeBACR_e_eBstWhlCntrlStsRrP__Sig_Signal},
		{"VeBACR_e_eBstWhlCntrlStsRrS", receive_eth_VeBACR_e_eBstWhlCntrlStsRrS__Sig_Signal},
		{"VeBACR_e_SbmPrimDiagStStsP", receive_eth_VeBACR_e_SbmPrimDiagStStsP__Sig_Signal},
		{"VeBACR_e_SbmPrimDiagStStsS", receive_eth_VeBACR_e_SbmPrimDiagStStsS__Sig_Signal},
		{"YeBACR_e_eBstEPB_StatusLtP", receive_eth_YeBACR_e_eBstEPB_StatusLtP__Sig_Signal},
		{"YeBACR_e_eBstEPB_StatusLtS", receive_eth_YeBACR_e_eBstEPB_StatusLtS__Sig_Signal},
		{"YeBACR_e_eBstEPB_StatusRtP", receive_eth_YeBACR_e_eBstEPB_StatusRtP__Sig_Signal},
		{"YeBACR_e_eBstEPB_StatusRtS", receive_eth_YeBACR_e_eBstEPB_StatusRtS__Sig_Signal},
		{"YeBACR_e_eBstEBOS_EBCMStateP", receive_eth_YeBACR_e_eBstEBOS_EBCMStateP__Sig_Signal},
		{"YeBACR_e_eBstEBOS_EBCMStateS", receive_eth_YeBACR_e_eBstEBOS_EBCMStateS__Sig_Signal},
	};

	std::unordered_map<std::string, std::reference_wrapper<decltype(receive_eth_VeBACR_F_eBstEPB_AchvdLtP__Sig_Signal)>> floatSignals
	{
		{"VeBACR_F_eBstEPB_AchvdLtP", receive_eth_VeBACR_F_eBstEPB_AchvdLtP__Sig_Signal},
		{"VeBACR_F_eBstEPB_AchvdLtS", receive_eth_VeBACR_F_eBstEPB_AchvdLtS__Sig_Signal},
		{"VeBACR_F_eBstEPB_AchvdRtP", receive_eth_VeBACR_F_eBstEPB_AchvdRtP__Sig_Signal},
		{"VeBACR_F_eBstEPB_AchvdRtS", receive_eth_VeBACR_F_eBstEPB_AchvdRtS__Sig_Signal},
		{"VeBACR_I_eBstBrkActCurr1_P", receive_eth_VeBACR_I_eBstBrkActCurr1_P__Sig_Signal},
		{"VeBACR_I_eBstBrkActCurr1_S", receive_eth_VeBACR_I_eBstBrkActCurr1_S__Sig_Signal},
		{"VeBACR_I_eBstBrkActCurr2_P", receive_eth_VeBACR_I_eBstBrkActCurr2_P__Sig_Signal},
		{"VeBACR_I_eBstBrkActCurr2_S", receive_eth_VeBACR_I_eBstBrkActCurr2_S__Sig_Signal},
		{"VeBACR_U_eBstBrkActVolt1_P", receive_eth_VeBACR_U_eBstBrkActVolt1_P__Sig_Signal},
		{"VeBACR_U_eBstBrkActVolt1_S", receive_eth_VeBACR_U_eBstBrkActVolt1_S__Sig_Signal},
		{"VeBACR_U_eBstBrkActVolt2_P", receive_eth_VeBACR_U_eBstBrkActVolt2_P__Sig_Signal},
		{"VeBACR_U_eBstBrkActVolt2_S", receive_eth_VeBACR_U_eBstBrkActVolt2_S__Sig_Signal},
		{"VeBACR_V_eBstHydCmpOffstVolP", receive_eth_VeBACR_V_eBstHydCmpOffstVolP__Sig_Signal},
		{"VeBACR_V_eBstHydCmpOffstVolS", receive_eth_VeBACR_V_eBstHydCmpOffstVolS__Sig_Signal},
		{"VeBACR_V_eBstPotPlngrVolP", receive_eth_VeBACR_V_eBstPotPlngrVolP__Sig_Signal},
		{"VeBACR_V_eBstPotPlngrVolS", receive_eth_VeBACR_V_eBstPotPlngrVolS__Sig_Signal},
		{"VeBACR_V_eBstRemPlngrVolP", receive_eth_VeBACR_V_eBstRemPlngrVolP__Sig_Signal},
		{"VeBACR_V_eBstRemPlngrVolS", receive_eth_VeBACR_V_eBstRemPlngrVolS__Sig_Signal},
		{"VeBACR_l_eBstMCP", receive_eth_VeBACR_l_eBstMCP__Sig_Signal},
		{"VeBACR_l_eBstMCS", receive_eth_VeBACR_l_eBstMCS__Sig_Signal},
		{"VeBACR_l_eBstPlngrPosnP", receive_eth_VeBACR_l_eBstPlngrPosnP__Sig_Signal},
		{"VeBACR_l_eBstPlngrPosnS", receive_eth_VeBACR_l_eBstPlngrPosnS__Sig_Signal},
		{"VeBACR_p_eBstBC_AchvdP", receive_eth_VeBACR_p_eBstBC_AchvdP__Sig_Signal},
		{"VeBACR_p_eBstBC_AchvdS", receive_eth_VeBACR_p_eBstBC_AchvdS__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstLfP", receive_eth_VeBACR_p_eBstBkPrsEstLfP__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstLfS", receive_eth_VeBACR_p_eBstBkPrsEstLfS__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstLrP", receive_eth_VeBACR_p_eBstBkPrsEstLrP__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstLrS", receive_eth_VeBACR_p_eBstBkPrsEstLrS__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstRfP", receive_eth_VeBACR_p_eBstBkPrsEstRfP__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstRfS", receive_eth_VeBACR_p_eBstBkPrsEstRfS__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstRrP", receive_eth_VeBACR_p_eBstBkPrsEstRrP__Sig_Signal},
		{"VeBACR_p_eBstBkPrsEstRrS", receive_eth_VeBACR_p_eBstBkPrsEstRrS__Sig_Signal},
		{"VeBACR_p_eBstMC_AchvdP", receive_eth_VeBACR_p_eBstMC_AchvdP__Sig_Signal},
		{"VeBACR_p_eBstMC_AchvdS", receive_eth_VeBACR_p_eBstMC_AchvdS__Sig_Signal},
		{"VeBACR_p_eBstVDA_PbcHPO_P", receive_eth_VeBACR_p_eBstVDA_PbcHPO_P__Sig_Signal},
		{"VeBACR_p_eBstVDA_PbcHPO_S", receive_eth_VeBACR_p_eBstVDA_PbcHPO_S__Sig_Signal},
		{"YeBACR_Pct_eBstThermalCapP", receive_eth_YeBACR_Pct_eBstThermalCapP__Sig_Signal},
		{"YeBACR_Pct_eBstThermalCapS", receive_eth_YeBACR_Pct_eBstThermalCapS__Sig_Signal},
	};

	signalGetRawList.clear();
	signalLenRawList.clear();
	Receive_Signal_Raw_List.clear();
	ReceiveSignalsList_Raw.clear();
	receiveHwU8SignalMap.clear();
	receiveHwU16SignalMap.clear();
	receiveHwU32SignalMap.clear();
	receiveHwI16SignalMap.clear();
	receiveHwFloatSignalMap.clear();
	receiveOldPhysValueMap.clear();

	for (const auto& ReceiveSignal : signals_xml)
	{
		signalGetRawList.emplace(ReceiveSignal.label, ReceiveSignal.get);
		signalLenRawList.emplace(ReceiveSignal.label, ReceiveSignal.length);

		auto RawIdVal = std::make_shared<IdValuePair<double>>();
		std::string RawCpName = ReceiveSignal.label + "__Sig";
		RawIdVal->Id = ReceiveSignal.get;
		RawIdVal->Name = ReceiveSignal.label;
		RawIdVal->Length = ReceiveSignal.length;
		RawIdVal->OldValue = ReceiveSignal.defValPhys > 0;
		Receive_Signal_Raw_List.emplace(RawCpName, RawIdVal);
		ReceiveSignalsList_Raw.emplace(RawCpName, ReceiveSignal);

		if (auto it = u8Signals.find(ReceiveSignal.label); it != u8Signals.end())
		{
			it->second.get().setAddress(ReceiveSignal.get);
			receiveHwU8SignalMap.emplace(RawCpName, it->second);

			LOG(INFO) << "Receive GetSignalsListData: added XML label=" << ReceiveSignal.label << " RawCpName=" << RawCpName << " to receiveHwU8SignalMap" << "Address: " << ReceiveSignal.get;
		}

		else if (auto it = u16Signals.find(ReceiveSignal.label); it != u16Signals.end())
		{
			it->second.get().setAddress(ReceiveSignal.get);
			receiveHwU16SignalMap.emplace(RawCpName, it->second);

			LOG(INFO) << "Receive GetSignalsListData: added XML label=" << ReceiveSignal.label << " RawCpName=" << RawCpName << " to receiveHwU16SignalMap" << "Address: " << ReceiveSignal.get;
		}

		else if (auto it = u32Signals.find(ReceiveSignal.label); it != u32Signals.end())
		{
			it->second.get().setAddress(ReceiveSignal.get);
			receiveHwU32SignalMap.emplace(RawCpName, it->second);

			LOG(INFO) << "Receive GetSignalsListData: added XML label=" << ReceiveSignal.label << " RawCpName=" << RawCpName << " to receiveHwU32SignalMap" << "Address: " << ReceiveSignal.get;
		}

		else if (auto it = i16Signals.find(ReceiveSignal.label); it != i16Signals.end())
		{
			it->second.get().setAddress(ReceiveSignal.get);
			receiveHwI16SignalMap.emplace(RawCpName, it->second);

			LOG(INFO) << "Receive GetSignalsListData: added XML label=" << ReceiveSignal.label << " RawCpName=" << RawCpName << " to receiveHwI16SignalMap" << "Address: " << ReceiveSignal.get;
		}

		else if (auto it = floatSignals.find(ReceiveSignal.label); it != floatSignals.end())
		{
			it->second.get().setAddress(ReceiveSignal.get);
			receiveHwFloatSignalMap.emplace(RawCpName, it->second);

			LOG(INFO) << "Receive GetSignalsListData: added XML label=" << ReceiveSignal.label << " RawCpName=" << RawCpName << " to receiveHwFloatSignalMap";
		}
		else
		{
			LOG(WARNING) << "Receive GetSignalsListData: no HwComDataObject found for XML label="
				<< ReceiveSignal.label;
		}
	}
}

void EID::Net::ETH::GM_BEV3_205_9p9_V01_M::ReceiveCore::ReceiveCore::PDUListData()
{
	auto pdus_xml = helper->Get_readxml()->GetSetPDUList(nodeName.c_str());

	for (const auto& sig : pdus_xml)
	{

		const unsigned int pduLengthBytes = sig.length / 8;

		PDUManipList.emplace(sig.label, sig.get);
		PDULengthList.emplace(sig.label, pduLengthBytes);

		auto getIdVal = std::make_shared<IdValuePair<double>>();
		std::string cpName = sig.label + "__PDU";
/*		getIdVal->Id = sig.get;
		getIdVal->Name = sig.label;
		getIdVal->Length = pduLengthBytes;
		PDUSetList.emplace(cpName, getIdVal);
		sendPDUList.emplace(cpName, sig);

		auto getIdVal = std::make_shared<IdValuePair<double>>();*/
		getIdVal->Id = sig.get;
		getIdVal->Name = sig.label;
		getIdVal->Length = pduLengthBytes;
		PDUGetList.emplace(cpName, getIdVal);
		receivePDUList.emplace(cpName, sig);

		//ETH1 Receive get
		if (sig.label == ETH1_WakeUp_PDU)
		{
			Receive_ETH1_PDU_WuP.setAddress(sig.get);

			CommonVars->EBCM_ETH1_WuP_PDU_Get_Address->quantity = none_t(Receive_ETH1_PDU_WuP.getAddress());
			CommonVars->EBCM_ETH1_WuP_PDU_Length->quantity = none_t(Receive_ETH1_PDU_WuP.getLength());
		}
		if (sig.label == ETH1_HeartBeat_PDU)
		{
			Receive_ETH1_PDU_Heartbeat.setAddress(sig.get);

			CommonVars->EBCM_ETH1_HB_PDU_Get_Address->quantity = none_t(Receive_ETH1_PDU_Heartbeat.getAddress());
			CommonVars->EBCM_ETH1_HB_PDU_Length->quantity = none_t(Receive_ETH1_PDU_Heartbeat.getLength());
		}
		if (sig.label == ETH1_Info_PDU)
		{
			Receive_ETH1_PDU_Info.setAddress(sig.get);

			CommonVars->EBCM_ETH1_Info_PDU_Get_Address->quantity = none_t(Receive_ETH1_PDU_Info.getAddress());
			CommonVars->EBCM_ETH1_Info_PDU_Length->quantity = none_t(Receive_ETH1_PDU_Info.getLength());
		}

		//ETH2 Receive get
		if (sig.label == ETH2_WakeUp_PDU)
		{
			Receive_ETH2_PDU_WuP.setAddress(sig.get);

			CommonVars->EBCM_ETH2_WuP_PDU_Get_Address->quantity = none_t(Receive_ETH2_PDU_WuP.getAddress());
			CommonVars->EBCM_ETH2_WuP_PDU_Length->quantity = none_t(Receive_ETH2_PDU_WuP.getLength());
		}
		if (sig.label == ETH2_HeartBeat_PDU)
		{
			Receive_ETH2_PDU_Heartbeat.setAddress(sig.get);

			CommonVars->EBCM_ETH2_HB_PDU_Get_Address->quantity = none_t(Receive_ETH2_PDU_Heartbeat.getAddress());
			CommonVars->EBCM_ETH2_HB_PDU_Length->quantity = none_t(Receive_ETH2_PDU_Heartbeat.getLength());
		}
		if (sig.label == ETH2_Info_PDU)
		{
			Receive_ETH2_PDU_Info.setAddress(sig.get);

			CommonVars->EBCM_ETH2_Info_PDU_Get_Address->quantity = none_t(Receive_ETH2_PDU_Info.getAddress());
			CommonVars->EBCM_ETH2_Info_PDU_Length->quantity = none_t(Receive_ETH2_PDU_Info.getLength());
		}
	}

	if (PDUGetList.empty())
	{
		LOG(INFO) << "ETH1 PDUGetList is empty.";
		return;
	}
}